import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const chatDrawerStyles = StyleSheet.create({
  dmSlidePanel: {
    position: "absolute",
    top: 0,
    bottom: 52,
    left: 0,
    right: 0,
    backgroundColor: "#080415",
    zIndex: 2000,
  },
  dmSafeArea: {
    flex: 1,
    backgroundColor: "#080415",
  },
  dmHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    height: 60,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#8b5cf6",
  },
  headerNameText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "bold",
  },
  headerUsernameText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 11,
    marginTop: -1,
  },
  socialContextContainer: {
    alignItems: "center",
    paddingVertical: 24,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
    marginBottom: 16,
  },
  socialContextAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: "#8b5cf6",
  },
  socialContextTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  socialContextUsername: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    marginBottom: 12,
  },
  socialContextSubtext: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12.5,
    textAlign: "center",
    lineHeight: 18,
  },
  socialContextBtn: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 16,
    marginTop: 14,
  },
  socialContextBtnText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
  },
  dmTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dmTitleText: {
    color: "#fff",
    fontSize: 18.5,
    fontWeight: "bold",
  },
  dmTitleRedDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#ff3b30",
  },
  dmSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#120d2c",
    borderRadius: 10,
    marginHorizontal: 16,
    marginVertical: 12,
    paddingHorizontal: 10,
    height: 38,
  },
  dmSearchIcon: {
    marginRight: 6,
  },
  dmSearchInput: {
    flex: 1,
    color: "#fff",
    fontSize: 15.5,
  },
  dmFilterStrip: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 12,
  },
  bizStoreEmptyCard: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    padding: 20,
    borderRadius: 16,
    backgroundColor: "#120d2c",
    borderWidth: 1,
    borderColor: "rgba(251,146,60,0.25)",
    alignItems: "center",
  },
  bizStoreEmptyTitle: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
    marginTop: 10,
  },
  bizStoreEmptyBody: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 14,
    textAlign: "center",
    marginTop: 6,
    lineHeight: 20,
  },
  bizStoreBar: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#120d2c",
    borderWidth: 1,
    borderColor: "rgba(0,245,255,0.15)",
  },
  bizStoreBarLabel: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  bizStoreBarMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  bizStoreBarAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
  },
  bizStoreBarName: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
  },
  bizStoreBarHandle: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 13,
    marginTop: 2,
  },
  bizStorePickerRow: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    gap: 10,
  },
  bizStoreChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 24,
    backgroundColor: "#120d2c",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    maxWidth: 180,
  },
  bizStoreChipActive: {
    borderColor: "#00f5ff66",
    backgroundColor: "#00f5ff12",
  },
  bizStoreChipAvatar: {
    width: 28,
    height: 28,
    borderRadius: 8,
  },
  bizStoreChipText: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 1,
  },
  bizStoreChipTextActive: {
    color: "#00f5ff",
  },
  bizStoreContextPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#120d2c",
    borderWidth: 1,
    marginBottom: 12,
  },
  bizStoreContextAvatar: {
    width: 40,
    height: 40,
    borderRadius: 10,
  },
  bizStoreContextAvatarPh: {
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  bizStoreContextInitial: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  bizStoreContextLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  bizStoreContextName: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    marginTop: 1,
  },
  bizStoreContextHandle: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 12.5,
    marginTop: 1,
  },
  bizStatCard: {
    backgroundColor: "#120d2c",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    minWidth: 90,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  bizStatValue: {
    fontSize: 20,
    fontWeight: "800",
    marginTop: 6,
  },
  bizStatLabel: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 13,
    marginTop: 3,
    textAlign: "center",
  },
  bizSectionLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 13.5,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
  },
  bizToolsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 12,
    gap: 10,
    marginBottom: 20,
  },
  bizToolCard: {
    backgroundColor: "#120d2c",
    borderRadius: 16,
    padding: 16,
    width: (width - 44) / 2,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  bizToolIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  bizToolName: {
    color: "#fff",
    fontSize: 15.5,
    fontWeight: "700",
  },
  bizToolDesc: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    marginTop: 3,
  },
  bizSubPanel: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 32,
  },
  bizSubBack: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  bizSubBackText: {
    color: "#00f5ff",
    fontSize: 16.5,
    marginLeft: 4,
    fontWeight: "600",
  },
  bizSubTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 4,
  },
  bizSubSubtitle: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 15.5,
    marginBottom: 16,
  },
  bizAudiencePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00f5ff15",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 7,
    alignSelf: "flex-start",
    marginBottom: 14,
  },
  bizBroadcastInput: {
    backgroundColor: "#120d2c",
    borderRadius: 12,
    color: "#fff",
    padding: 14,
    fontSize: 16.5,
    borderWidth: 1,
    borderColor: "rgba(0,245,255,0.2)",
    textAlignVertical: "top",
    minHeight: 110,
    marginBottom: 14,
  },
  bizSendBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#00f5ff",
    borderRadius: 12,
    paddingVertical: 13,
  },
  bizSendBtnText: {
    color: "#000",
    fontWeight: "800",
    fontSize: 16.5,
  },
  bizSuccessBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#34d39915",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#34d39933",
  },
  bizPromoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#120d2c",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  bizAdCard: {
    backgroundColor: "#120d2c",
    borderRadius: 14,
    padding: 14,
    width: 200,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  bizTagBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginLeft: 6,
  },
  bizTagText: {
    fontSize: 13,
    fontWeight: "600",
  },
  bizUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#00f5ff",
    marginLeft: 8,
  },
  bizAutoReplyToggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  bizToggle: {
    width: 46,
    height: 26,
    borderRadius: 13,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 3,
  },
  bizToggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  bizCatalogueItem: {
    width: (width - 76) / 3,
    backgroundColor: "#120d2c",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  bizCatalogueImg: {
    width: "100%",
    height: 90,
  },
  bizCatalogueName: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
    padding: 6,
  },
  bizCataloguePrice: {
    color: "#00f5ff",
    fontSize: 13,
    paddingHorizontal: 6,
    paddingBottom: 6,
  },
  dmFilterTab: {
    backgroundColor: "#120d2c",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  dmFilterTabActive: {
    backgroundColor: "#fff",
  },
  dmFilterText: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 13.5,
    fontWeight: "bold",
  },
  dmFilterTextActive: {
    color: "#000",
  },
  dmThreadsScroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  threadItemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderColor: "rgba(255,255,255,0.06)",
  },
  threadAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  threadDetails: {
    flex: 1,
    marginLeft: 12,
  },
  threadNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  threadNameText: {
    color: "#fff",
    fontSize: 15.5,
    fontWeight: "600",
  },
  verifiedCheck: {
    marginLeft: 2,
  },
  threadMessageText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13.5,
    marginTop: 2,
  },
  threadMessageTextUnread: {
    color: "#fff",
    fontWeight: "bold",
  },
  cameraIconBtn: {
    padding: 8,
  },
  chatFeedScroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  chatFeedContent: {
    paddingBottom: 24,
    paddingTop: 16,
  },
  chatStartText: {
    color: "rgba(255,255,255,0.25)",
    fontSize: 12.5,
    textAlign: "center",
    marginBottom: 20,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  msgRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginBottom: 16,
    gap: 8,
    maxWidth: "80%",
  },
  msgRowLeft: {
    alignSelf: "flex-start",
  },
  msgRowRight: {
    alignSelf: "flex-end",
    flexDirection: "row-reverse",
  },
  msgAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#00f5ff",
    alignItems: "center",
    justifyContent: "center",
  },
  msgAvatarText: {
    color: "#000",
    fontWeight: "bold",
    fontSize: 13,
  },
  msgBubble: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 18,
  },
  msgBubbleLeft: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderBottomLeftRadius: 4,
  },
  msgBubbleRight: {
    backgroundColor: "#8b5cf6",
    borderBottomRightRadius: 4,
  },
  msgText: {
    fontSize: 15.5,
    lineHeight: 18,
  },
  msgTextLeft: {
    color: "#fff",
  },
  msgTextRight: {
    color: "#fff",
    fontWeight: "500",
  },


  typingContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 6,
    gap: 8,
  },
  typingDotWrap: {
    flexDirection: "row",
    gap: 3,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#00f5ff",
  },
  typingText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    fontStyle: "italic",
  },
  newChatOverlay: {
    flex: 1,
    backgroundColor: "#080415",
  },
  newChatSafeArea: {
    flex: 1,
  },
  newChatHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    paddingHorizontal: 16,
    height: 48,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  newChatTitle: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold" as const,
  },
  newChatSearchContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingHorizontal: 16,
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  newChatSearchTo: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600" as const,
    marginRight: 12,
  },
  newChatSearchInput: {
    flex: 1,
    color: "#fff",
    fontSize: 16,
  },
  newChatSuggestedTitle: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 12.5,
    fontWeight: "bold" as const,
    letterSpacing: 0.5,
    marginTop: 20,
    marginBottom: 8,
    paddingHorizontal: 16,
  },
  newChatEmptyText: {
    color: "rgba(255,255,255,0.35)",
    fontSize: 15,
    textAlign: "center" as const,
    marginTop: 40,
  },
  newChatUserRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  newChatAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  newChatAvatarFallback: {
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  newChatName: {
    color: "#fff",
    fontSize: 15.5,
    fontWeight: "600" as const,
  },
  newChatUsername: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13.5,
    marginTop: 1,
  },
  callOverlayContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  callSafeArea: {
    flex: 1,
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 50,
    zIndex: 10,
  },
  callProfileCard: {
    alignItems: "center",
    marginTop: 40,
    gap: 16,
  },
  callAvatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 3,
    borderColor: "#00f5ff",
  },
  callName: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "bold",
  },
  callStatusText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 15,
  },
  callControlsRow: {
    flexDirection: "row",
    gap: 40,
    marginBottom: 20,
  },
  callBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  acceptBtn: {
    backgroundColor: "#10b981",
  },
  declineBtn: {
    backgroundColor: "#ef4444",
  },
  endCallBtn: {
    backgroundColor: "#ef4444",
  },
  localVideoBox: {
    position: "absolute",
    top: 50,
    right: 20,
    width: 100,
    height: 150,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "#00f5ff",
    backgroundColor: "#000",
    zIndex: 100,
  },
  attachMenuBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  attachMenuContent: {
    backgroundColor: "#0c0822",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 40,
    paddingTop: 12,
  },
  attachMenuHeader: {
    alignItems: "center",
    marginBottom: 10,
  },
  attachMenuHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  attachMenuTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  attachOptionsGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 20,
  },
  attachOptionBtn: {
    alignItems: "center",
    gap: 8,
  },
  attachIconBg: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  attachOptionLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: "600",
  },
  shareProductItem: {
    backgroundColor: "#120d2c",
    width: 110,
    borderRadius: 12,
    padding: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  shareProductImg: {
    width: 90,
    height: 90,
    borderRadius: 8,
    marginBottom: 6,
  },
  shareProductTitle: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
    width: "100%",
    textAlign: "center",
  },
  shareProductPrice: {
    color: "#00f5ff",
    fontSize: 11.5,
    fontWeight: "bold",
    marginTop: 2,
  },
  msgImageContainer: {
    borderRadius: 14,
    overflow: "hidden",
    maxWidth: 220,
    height: 150,
  },
  msgImage: {
    width: "100%",
    height: "100%",
  },
  msgGif: {
    width: 180,
    height: 180,
    borderRadius: 12,
  },
  msgLocationContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 6,
  },
  msgLocationText: {
    color: "#00f5ff",
    fontSize: 14,
    textDecorationLine: "underline",
  },
  msgProductCard: {
    flexDirection: "row",
    backgroundColor: "#120d2c",
    borderRadius: 12,
    padding: 10,
    width: 220,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  msgProductImage: {
    width: 70,
    height: 70,
    borderRadius: 8,
  },
  msgProductName: {
    color: "#fff",
    fontSize: 13.5,
    fontWeight: "bold",
  },
  msgProductPrice: {
    color: "#00f5ff",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 2,
    marginBottom: 6,
  },
  msgProductBuyBtn: {
    backgroundColor: "#00f5ff",
    borderRadius: 6,
    paddingVertical: 5,
    alignItems: "center",
  },
  msgProductBuyText: {
    color: "#000",
    fontSize: 11,
    fontWeight: "bold",
  },
  chatInputBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#080415",
  },
  cameraCircleBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#8b5cf6",
    alignItems: "center",
    justifyContent: "center",
  },
  inputCapsule: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 20,
    paddingHorizontal: 12,
    height: 40,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  capsuleInput: {
    flex: 1,
    color: "#fff",
    fontSize: 14.5,
    paddingVertical: 0,
    height: "100%",
  },
  chatSendText: {
    color: "#00f5ff",
    fontWeight: "bold",
    fontSize: 15,
    paddingHorizontal: 4,
  },
  attachVerticalList: {
    paddingHorizontal: 24,
    gap: 14,
    paddingTop: 10,
    paddingBottom: 30,
  },
  attachVerticalItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
    paddingVertical: 8,
    gap: 16,
  },
  attachVerticalLabel: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  attachVerticalSubtext: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 12.5,
    marginTop: 2,
  },
  bubbleReplyPreview: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderLeftWidth: 3,
    borderLeftColor: "#00f5ff",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginBottom: 6,
    opacity: 0.85,
  },
  bubbleReplyText: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 12.5,
    fontStyle: "italic",
  },
  bubbleReactionsRow: {
    flexDirection: "row",
    gap: 3,
    backgroundColor: "#1c1c1e",
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#080415",
    position: "absolute",
    bottom: -11,
    right: 8,
    zIndex: 10,
  },
  longPressBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.65)",
    justifyContent: "center",
    alignItems: "center",
  },
  longPressContainer: {
    width: "80%",
    alignItems: "center",
    gap: 16,
  },
  reactionPillContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1c1c1e",
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 20,
    gap: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  reactionEmojiText: {
    fontSize: 24,
  },
  longPressOptionsCard: {
    width: "100%",
    backgroundColor: "#1c1c1e",
    borderRadius: 24,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
  },
  longPressTimestamp: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 12,
    textAlign: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  longPressOptionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
  },
  longPressOptionLabel: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  replyPreviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
  },
  replyPreviewTitle: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 13,
    flex: 1,
  },
  msgStatusText: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    marginTop: 2.5,
    marginRight: 6,
  },
  labelSheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.65)",
    justifyContent: "flex-end",
  },
  labelSheetContent: {
    backgroundColor: "#1c1c1e",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  labelSheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignSelf: "center",
    marginBottom: 16,
  },
  labelSheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  labelSheetTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    flex: 1,
    textAlign: "center",
    marginLeft: 40,
  },
  labelSheetClearText: {
    color: "#3b82f6",
    fontSize: 16,
    fontWeight: "bold",
    width: 40,
  },
  labelOptionsList: {
    maxHeight: 320,
  },
  labelOptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
  },
  labelOptionLabel: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  labelRadioCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  labelRadioCircleActive: {
    borderColor: "#3b82f6",
    backgroundColor: "#3b82f6",
  },
  labelRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
  },
  labelSheetFooterText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 12.5,
    textAlign: "center",
    marginVertical: 16,
    lineHeight: 18,
  },
  labelSaveBtn: {
    backgroundColor: "#3b82f6",
    borderRadius: 12,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  labelSaveBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  coinPopupBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.82)",
    justifyContent: "center",
    alignItems: "center",
  },
  coinCardContainer: {
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: "#16161a",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "rgba(0, 245, 255, 0.45)",
    shadowColor: "#00f5ff",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  coinWrapper: {
    width: "100%",
    height: "100%",
  },
  coinFace: {
    width: "100%",
    height: "100%",
    borderRadius: 120,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  coinFaceFront: {
    backgroundColor: "#000",
  },
  coinFaceBack: {
    backgroundColor: "#1c1c24",
    padding: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  coinPhoto: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  coinFrontOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.65)",
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  coinFrontName: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  coinFrontUsername: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    textAlign: "center",
    marginTop: 1,
  },
  coinFlipHint: {
    color: "#00f5ff",
    fontSize: 9,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 4,
  },
  coinBackHeader: {
    marginBottom: 12,
    alignItems: "center",
  },
  coinBackTitle: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 11,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  coinStoreRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 60,
    width: 200,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  coinStoreLogo: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#000",
  },
  coinStoreName: {
    color: "#fff",
    fontSize: 12.5,
    fontWeight: "bold",
  },
  coinStoreSubtext: {
    color: "#00f5ff",
    fontSize: 9.5,
    fontWeight: "600",
    marginTop: 1,
  },
  coinNoStoresContainer: {
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  coinNoStoresText: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 12,
    textAlign: "center",
  },
  coinViewProfileBtn: {
    backgroundColor: "#3b82f6",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    marginTop: 6,
  },
  coinViewProfileBtnText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "bold",
  },
  collabInviteCard: {
    flexDirection: "row",
    gap: 10,
    maxWidth: 280,
    padding: 4,
  },
  collabInviteThumb: {
    width: 72,
    height: 72,
    borderRadius: 8,
    backgroundColor: "#111",
  },
  collabInviteTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  collabInviteSub: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 12,
    marginTop: 4,
    lineHeight: 16,
  },
  collabInviteActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  collabInviteAcceptBtn: {
    backgroundColor: "#00f5ff",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
  },
  collabInviteAcceptText: {
    color: "#080415",
    fontWeight: "700",
    fontSize: 13,
  },
  collabInviteDeclineBtn: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  collabInviteDeclineText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 13,
  },
  collabInviteStatusOk: {
    color: "#34d399",
    fontWeight: "700",
    fontSize: 12,
    marginTop: 8,
  },
  collabInviteStatusNo: {
    color: "rgba(255,255,255,0.45)",
    fontWeight: "600",
    fontSize: 12,
    marginTop: 8,
  },
  collabInvitePending: {
    color: "#fbbf24",
    fontWeight: "600",
    fontSize: 12,
    marginTop: 8,
  },
  bizToggleGroup: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 3,
    marginBottom: 14,
  },
  bizToggleBtn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderRadius: 10,
  },
  bizToggleBtnActive: {
    backgroundColor: "#818cf822",
  },
  bizToggleText: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 12,
    fontWeight: "700",
  },
  bizToggleTextActive: {
    color: "#818cf8",
  },
  bizFieldLabel: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
    marginTop: 4,
  },
  bizCreatorChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  bizCreatorChipActive: {
    borderColor: "#818cf8",
    backgroundColor: "#818cf815",
  },
});;
