import { StyleSheet } from "react-native";

export const profileHeaderStyles = StyleSheet.create({
  canvasHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 10,
    backgroundColor: "transparent",
  },
  canvasHeaderDropdown: {
    flexDirection: "row",
    alignItems: "center",
  },
  canvasHeaderUsername: {
    color: "#ffffff",
    fontSize: 21,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  canvasHeaderRightIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  avatarStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  avatarGroup: {
    position: "relative",
    width: 88,
    height: 88,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitial: {
    color: "#ffffff",
    fontSize: 32,
    fontWeight: "300",
    fontFamily: "System",
  },
  avatarPlusBadge: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#00f5ff", // Sleek AURA blue
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#080415",
  },
  bubbleOverlay: {
    position: "absolute",
    top: -24,
    backgroundColor: "#0b071e",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    zIndex: 100,
    alignItems: "center",
  },
  bubbleText: {
    color: "#00f5ff",
    fontSize: 10.5,
    fontWeight: "500",
  },
  bubblePointer: {
    position: "absolute",
    bottom: -4,
    width: 8,
    height: 8,
    backgroundColor: "#0b071e",
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    transform: [{ rotate: "45deg" }],
  },
  statsRow: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "space-around",
    paddingLeft: 12,
  },
  statItem: {
    alignItems: "center",
  },
  statNumber: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  statLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12.5,
    fontWeight: "400",
    marginTop: 2,
  },
  bioContainer: {
    marginTop: 12,
  },
  bioBrandName: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
  },
  bioCategory: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13.5,
    fontWeight: "400",
    marginTop: 2,
  },
  bioDescriptionText: {
    color: "#ffffff",
    fontSize: 13.5,
    lineHeight: 18.5,
    marginTop: 5,
    fontWeight: "500",
  },
  websiteRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    gap: 4,
  },
  websiteText: {
    color: "#00f5ff",
    fontSize: 13.5,
    fontWeight: "bold",
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
  },
  tagBadge: {
    backgroundColor: "rgba(255,255,255,0.02)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 12,
    paddingVertical: 5.5,
    borderRadius: 14,
  },
  tagBadgeText: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 11.5,
    fontWeight: "600",
  },
  addTagBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 5.5,
    borderRadius: 14,
  },
  addTagBtnText: {
    color: "#00f5ff",
    fontSize: 11.5,
    fontWeight: "bold",
  },
  dashboardCard: {
    backgroundColor: "rgba(255,255,255,0.035)", // High-end translucent glass card
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginHorizontal: 16,
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dashboardTitle: {
    color: "#ffffff",
    fontSize: 13.5,
    fontWeight: "bold",
  },
  dashboardSubtitle: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 12,
    marginTop: 2,
  },
  dashboardIndicatorDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: "#00f5ff",
  },
  actionButtonsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginTop: 14,
    gap: 8,
  },
  actionBtn: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.07)", // Translucent premium grey
    borderRadius: 10, // Modern rounded corners
    height: 34,
    justifyContent: "center",
    alignItems: "center",
  },
  actionBtnText: {
    color: "#ffffff",
    fontSize: 13.5,
    fontWeight: "600",
  },
  highlightsContainer: {
    marginTop: 20,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingBottom: 16,
  },
  highlightsScroll: {
    paddingHorizontal: 16,
    gap: 16,
  },
  highlightItem: {
    alignItems: "center",
    width: 64,
  },
  highlightPlusCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  highlightCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.08)",
    padding: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  highlightImage: {
    width: "100%",
    height: "100%",
    borderRadius: 27,
  },
  highlightTitle: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    marginTop: 5,
    textAlign: "center",
  },
  creatorBannerCard: {
    backgroundColor: "rgba(0,245,255,0.04)", // Light neon cyan glass background
    borderWidth: 0.5,
    borderColor: "rgba(0,245,255,0.15)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginHorizontal: 16,
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  auraBadgeCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#00f5ff",
    justifyContent: "center",
    alignItems: "center",
  },
  auraBadgeText: {
    color: "#080415",
    fontSize: 9,
    fontWeight: "900",
  },
  creatorBannerTitle: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "bold",
  },
  creatorBannerScore: {
    color: "#00f5ff",
    fontSize: 11.5,
    marginTop: 2,
  },
  creatorBadgeBtn: {
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  creatorBadgeBtnText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "bold",
  },
  threadsPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 10,
    paddingVertical: 5.5,
    borderRadius: 30,
    alignSelf: "flex-start",
    marginTop: 12,
  },
  threadsIcon: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "bold",
    marginRight: 4,
  },
  threadsPillText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  editModalContainer: {
    flex: 1,
    backgroundColor: "#080415",
  },
  editModalNavBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#080415",
  },
  editModalCancelText: {
    color: "#ffffff",
    fontSize: 15.5,
  },
  editModalTitle: {
    color: "#ffffff",
    fontSize: 16.5,
    fontWeight: "bold",
  },
  editModalDoneText: {
    color: "#00f5ff",
    fontSize: 15.5,
    fontWeight: "bold",
  },
  editModalScroll: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 18,
    backgroundColor: "#080415",
  },
  editModalAvatarContainer: {
    alignItems: "center",
    marginBottom: 24,
  },
  editModalAvatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#0b071e",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.06)",
  },
  editModalAvatarText: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "300",
  },
  editModalChangeAvatarText: {
    color: "#00f5ff",
    fontSize: 13.5,
    fontWeight: "bold",
    marginTop: 10,
  },
  inputGroup: {
    marginBottom: 16,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingBottom: 8,
  },
  inputLabel: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 11.5,
    textTransform: "uppercase",
    fontWeight: "bold",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  inputField: {
    color: "#ffffff",
    fontSize: 14.5,
    paddingVertical: 4,
  },
});
