import { StyleSheet } from "react-native";

export const profileModalStyles = StyleSheet.create({
  switcherBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  switcherPanel: {
    backgroundColor: "#0b071e",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: "80%",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  switcherHandle: {
    width: 40,
    height: 4,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  switcherTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
    textAlign: "center",
  },
  switcherList: {
    marginBottom: 20,
  },
  switcherItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  switcherItemActive: {
    backgroundColor: "rgba(0, 245, 255, 0.05)",
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  switcherAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#20183e",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  switcherAvatarActive: {
    borderColor: "#00f5ff",
    borderWidth: 1.5,
  },
  switcherAvatarText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 14,
  },
  switcherInfo: {
    flex: 1,
    marginLeft: 12,
  },
  switcherMaisonId: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  switcherMaisonName: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
  },
  switcherCheck: {
    paddingLeft: 10,
  },
  addBrandBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(0, 245, 255, 0.3)",
    borderRadius: 8,
    marginTop: 10,
  },
  addBrandBtnText: {
    color: "#00f5ff",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 8,
  },
  createPanel: {
    backgroundColor: "#0b071e",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: "80%",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  createTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 20,
    textAlign: "center",
  },
  createList: {
    marginBottom: 10,
  },
  createItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  createItemText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "500",
    marginLeft: 14,
    flex: 1,
  },
  bottomSheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  bottomSheetDragHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignSelf: "center",
    marginVertical: 12,
  },
  shareSheetContent: {
    backgroundColor: "#0d0a21",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingVertical: 8,
    paddingBottom: 32,
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
  },
  shareSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 10,
    gap: 12,
  },
  shareSearchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 40,
    gap: 8,
  },
  shareSearchInput: {
    flex: 1,
    color: "#fff",
    fontSize: 14,
  },
  shareAddFriendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  shareContactsContainer: {
    paddingHorizontal: 20,
    marginTop: 20,
    gap: 20,
  },
  shareContactsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  shareContactCard: {
    alignItems: "center",
    width: 90,
  },
  shareContactAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.1)",
  },
  shareContactName: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 11,
    fontWeight: "500",
    marginTop: 8,
    textAlign: "center",
  },
  shareHorizontalDivider: {
    height: 0.5,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginVertical: 20,
  },
  shareActionsScroll: {
    paddingHorizontal: 20,
    gap: 20,
  },
  shareActionBtn: {
    alignItems: "center",
    width: 76,
    gap: 6,
  },
  shareActionCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  shareActionLabel: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 10,
    textAlign: "center",
    fontWeight: "500",
  },
  promptOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  promptContainer: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#0b071e",
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
  },
  promptTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 8,
  },
  promptDesc: {
    color: "rgba(255, 255, 255, 0.5)",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 16,
  },
  promptInput: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 8,
    color: "#ffffff",
    fontSize: 14,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 20,
  },
  promptActionRow: {
    flexDirection: "row",
    gap: 12,
  },
  promptButton: {
    flex: 1,
    height: 44,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  promptCancelButton: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  promptSubmitButton: {
    backgroundColor: "#00f5ff",
  },
  promptCancelButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  promptSubmitButtonText: {
    color: "#080415",
    fontSize: 14,
    fontWeight: "bold",
  },
  wishlistOverlay: {
    flex: 1,
    backgroundColor: "rgba(8, 4, 21, 0.95)",
    justifyContent: "flex-end",
  },
  wishlistContainer: {
    height: "80%",
    backgroundColor: "#0b071e",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingTop: 24,
    paddingHorizontal: 20,
  },
  wishlistHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
    paddingBottom: 16,
  },
  wishlistTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 2,
  },
  wishlistListContent: {
    paddingBottom: 40,
    gap: 16,
  },
  wishlistItemCard: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
    padding: 12,
    gap: 12,
  },
  wishlistItemMain: {
    flexDirection: "row",
    alignItems: "center",
  },
  wishlistItemImg: {
    width: 80,
    height: 80,
    borderRadius: 16,
    resizeMode: "cover",
  },
  wishlistItemInfo: {
    flex: 1,
    marginLeft: 16,
    gap: 2,
  },
  wishlistItemMaison: {
    color: "rgba(255, 255, 255, 0.4)",
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  wishlistItemTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  wishlistItemVibe: {
    color: "#00f5ff",
    fontSize: 11,
    fontWeight: "500",
  },
  wishlistItemPrice: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
  },
  wishlistItemActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.04)",
    paddingTop: 10,
  },
  wishlistAddToCartBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00f5ff",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  wishlistAddToCartText: {
    color: "#000000",
    fontSize: 12,
    fontWeight: "700",
  },
  wishlistRemoveBtn: {
    padding: 8,
  },
  wishlistEmpty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 60,
    gap: 12,
  },
  wishlistEmptyTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  wishlistEmptyDesc: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    textAlign: "center",
    paddingHorizontal: 32,
    lineHeight: 18,
  },
});
