import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const homeModalStyles = StyleSheet.create({
  storyModalContainer: {
    flex: 1,
    backgroundColor: "#080415",
  },
  storyTapDetector: {
    position: "absolute",
    top: 100,
    bottom: 100,
    width: width * 0.35,
    zIndex: 100,
  },
  storyModalSafe: {
    flex: 1,
    justifyContent: "space-between",
  },
  storyProgressStrip: {
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  storyProgressBarBg: {
    flex: 1,
    height: 2,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 1,
    overflow: "hidden",
  },
  storyProgressBarFill: {
    height: "100%",
    backgroundColor: "#fff",
  },
  storyModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    zIndex: 200,
  },
  storyHeaderAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fff",
  },
  storyHeaderUsername: {
    color: "#fff",
    fontSize: 14.5,
    fontWeight: "bold",
  },
  storyHeaderTime: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 13.5,
  },
  storySlideContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  storySlideImage: {
    width: width,
    height: height * 0.6,
    resizeMode: "cover",
  },
  storySlideCaptionOverlay: {
    position: "absolute",
    bottom: 24,
    left: 20,
    right: 20,
    backgroundColor: "rgba(0,0,0,0.6)",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  storySlideCaptionText: {
    color: "#fff",
    fontSize: 15,
    textAlign: "center",
    lineHeight: 18,
  },
  storyReplyFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 20,
    paddingTop: 10,
    zIndex: 200,
  },
  storyReplyInput: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 16,
    color: "#fff",
    fontSize: 15.5,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  storyReplySendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  settlementOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  settlementCardGlow: {
    borderRadius: 24,
    padding: 1.5,
    backgroundColor: "rgba(0, 245, 255,  0.2)",
    borderWidth: 1,
    borderColor: "rgba(0, 245, 255,  0.3)",
    width: "100%",
  },
  settlementCard: {
    backgroundColor: "#0d0822",
    borderRadius: 23,
    padding: 24,
    alignItems: "center",
    gap: 20,
  },
  settlementHeader: {
    alignItems: "center",
    gap: 6,
  },
  settlementTitle: {
    color: "#fff",
    fontSize: 18.5,
    fontWeight: "bold",
    textAlign: "center",
  },
  settlementSubtitle: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 11.5,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
    textAlign: "center",
  },
  settlementGrid: {
    width: "100%",
    backgroundColor: "#0b071e",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
    padding: 16,
    gap: 12,
  },
  settlementRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  settlementLabel: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 13,
    fontWeight: "500",
  },
  settlementValue: {
    color: "#fff",
    fontSize: 13.5,
    fontWeight: "bold",
  },
  settlementFootnote: {
    color: "rgba(255,255,255,0.25)",
    fontSize: 11,
    textAlign: "center",
    lineHeight: 12,
    paddingHorizontal: 12,
  },
  settlementCloseBtn: {
    backgroundColor: "#00f5ff",
    paddingVertical: 14,
    borderRadius: 16,
    width: "100%",
    alignItems: "center",
  },
  settlementCloseBtnText: {
    color: "#000",
    fontSize: 14.5,
    fontWeight: "bold",
  },
  bottomSheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  optionsBottomSheetContent: {
    backgroundColor: "#0d0a21",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingVertical: 8,
    paddingBottom: 32,
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
  },
  bottomSheetDragHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignSelf: "center",
    marginVertical: 12,
  },
  optionsGroupContainer: {
    backgroundColor: "rgba(255,255,255,0.035)",
    borderRadius: 16,
    marginHorizontal: 16,
    marginVertical: 6,
    overflow: "hidden",
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.06)",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  optionRowText: {
    color: "#fff",
    fontSize: 15.5,
    fontWeight: "500",
  },
  optionDivider: {
    height: 0.5,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginHorizontal: 20,
  },
  commentsOverlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  commentsSheetContent: {
    backgroundColor: "#0d0a21",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
  },
  commentsHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
  },
  commentsHeaderTitle: {
    color: "#fff",
    fontSize: 16.5,
    fontWeight: "bold",
  },
  commentsScroll: {
    flex: 1,
    marginTop: 12,
  },
  commentRow: {
    flexDirection: "row",
    gap: 12,
    marginVertical: 10,
    alignItems: "flex-start",
  },
  commentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#00f5ff",
    alignItems: "center",
    justifyContent: "center",
  },
  commentAvatarText: {
    color: "#000",
    fontSize: 14.5,
    fontWeight: "bold",
  },
  commentUsername: {
    color: "#fff",
    fontSize: 13.5,
    fontWeight: "bold",
    marginBottom: 2,
    flexDirection: "row",
    alignItems: "center",
  },
  commentBadge: {
    color: "#00f5ff",
    fontSize: 11,
    fontWeight: "bold",
    textTransform: "uppercase",
    borderWidth: 0.5,
    borderColor: "#00f5ff",
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginLeft: 6,
  },
  commentTextContent: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 14.5,
    lineHeight: 16,
  },
  commentTime: {
    color: "rgba(255,255,255,0.35)",
    fontSize: 13,
    marginTop: 4,
  },
  commentsSeparator: {
    height: 0.5,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginVertical: 10,
  },
  commentsInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#0d0a21",
  },
  commentTextInput: {
    flex: 1,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 16,
    color: "#fff",
    fontSize: 14.5,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  commentPostBtnText: {
    color: "#00f5ff",
    fontSize: 14.5,
    fontWeight: "bold",
  },
});
