import { StyleSheet } from "react-native";

export const homeNewPostStyles = StyleSheet.create({
  dmSlidePanel: {
    position: "absolute",
    top: 0,
    bottom: 62,
    left: 0,
    right: 0,
    backgroundColor: "#080415",
    zIndex: 2000,
  },
  dmSafeArea: {
    flex: 1,
    backgroundColor: "#080415",
  },
  newPostHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderColor: "rgba(255,255,255,0.06)",
  },
  newPostHeaderTitle: {
    color: "#fff",
    fontSize: 18.5,
    fontWeight: "bold",
  },
  newPostScroll: {
    flex: 1,
  },
  newPostMediaPreview: {
    width: "100%",
    height: 200,
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  newPostMediaImg: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  newPostCaptionWrap: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    minHeight: 80,
  },
  newPostCaptionInput: {
    color: "#fff",
    fontSize: 16.5,
    lineHeight: 20,
  },
  newPostChipsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 10,
    marginBottom: 12,
  },
  newPostChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  newPostChipText: {
    color: "#fff",
    fontSize: 14.5,
    fontWeight: "600",
  },
  newPostDivider: {
    height: 0.5,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginHorizontal: 16,
  },
  newPostOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  newPostOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    flex: 1,
  },
  newPostOptionRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  newPostOptionText: {
    color: "#fff",
    fontSize: 16.5,
  },
  newPostOptionSub: {
    color: "rgba(255,255,255,0.35)",
    fontSize: 13.5,
    marginTop: 3,
    lineHeight: 15,
  },
  newPostOptionValue: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 15.5,
  },
  newPostAudioTrack: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: "#120d2c",
    borderRadius: 12,
    padding: 10,
  },
  newPostAudioThumb: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#333",
  },
  newPostAudioName: {
    color: "#fff",
    fontSize: 14.5,
    fontWeight: "600",
    flex: 1,
  },
  newPostToggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#333",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  newPostToggleActive: {
    backgroundColor: "#4a90d9",
  },
  newPostToggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#888",
  },
  newPostToggleThumbActive: {
    backgroundColor: "#fff",
    alignSelf: "flex-end",
  },
  newPostProductList: {
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: "#120d2c",
    borderRadius: 12,
    overflow: "hidden",
  },
  newPostProductItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderColor: "rgba(255,255,255,0.06)",
  },
  newPostProductItemActive: {
    backgroundColor: "rgba(0,245,255,0.15)",
  },
  newPostProductName: {
    color: "#fff",
    fontSize: 14.5,
    flex: 1,
    marginRight: 8,
  },
  newPostProductPrice: {
    color: "#00f5ff",
    fontSize: 13.5,
    fontWeight: "bold",
  },
  newPostProductEmpty: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 13.5,
    padding: 16,
    textAlign: "center",
  },
  newPostShareBtnWrap: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 0.5,
    borderColor: "rgba(255,255,255,0.06)",
  },
  newPostShareBtn: {
    backgroundColor: "#4a90d9",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  newPostShareBtnText: {
    color: "#fff",
    fontSize: 17.5,
    fontWeight: "bold",
  },
  newPostInlineInput: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: "#120d2c",
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 44,
    gap: 8,
  },
  newPostInlineTextInput: {
    flex: 1,
    color: "#fff",
    fontSize: 15.5,
  },
  autocompleteList: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: "#120d2c",
    borderRadius: 12,
    overflow: "hidden",
    maxHeight: 180,
  },
  autocompleteItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderColor: "rgba(255,255,255,0.06)",
    gap: 10,
  },
  autocompleteAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  autocompleteCover: {
    width: 28,
    height: 28,
    borderRadius: 6,
  },
  autocompleteLocationIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0,245,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  autocompleteText: {
    color: "#fff",
    fontSize: 15.5,
    fontWeight: "600",
  },
  autocompleteSub: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
  },
  advancedOptionsContainer: {
    backgroundColor: "#121214",
    marginHorizontal: 16,
    borderRadius: 16,
    paddingVertical: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
});
